문제점: data_merger.py connec가 아닌 요청을 받는 방법으로 변환